name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-1
          role-session-name: GitHub-OIDC-ECS

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: <${{ secrets.AWS_ACCOUNT_ID }}>.dkr.ecr.<${{ secrets.AWS_REGION }}>.amazonaws.com/<${{ secrets.AWS_ECR_REPO_NAME }}>:latest

#     - name: Deploy to ECS
#       uses: aws-actions/ecs-deploy@v1
#       with:
#         cluster: <${{ secrets.CLUSTER_NAME }}>
#         service: <${{ secrets.SERVICE_NAME }}>
#         image: <${{ secrets.AWS_ACCOUNT_ID }}>.dkr.ecr.<${{ secrets.AWS_REGION }}>.amazonaws.com/<${{ secrets.AWS_ECR_REPO_NAME }}>:latest
        
    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
#         task-definition: task-definition.json
        service: <${{ secrets.SERVICE_NAME }}>
        cluster: <${{ secrets.CLUSTER_NAME }}>
        wait-for-service-stability: true
